# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DATABASE_URL: postgresql://gary:gar123@localhost:5432/garment_app

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    services:
      postgres:
        image: postgres:latest
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5s
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm install -g npm
    - run: npm install
    - run: |
        psql -h postgres -U postgres -c 'create database garment_app;'
        psql -h postgres -U postgres -c 'create role gary login password 'gar123';'   
        psql -h postgres -U postgres -c 'grant all privileges on database garment_app to gary;'
        psql -U postgres -d garment_app -a -f ./sql/garment.sql
        psql -U postgres -d garment_app -a -f ./sql/data.sql
    - run: npm run build --if-present
    - run: npm test
